### ISSUE TITLE
Can't access interactive tutorial

### ISSUE THREAD

**Issue by rcwestlake** [learnapollo/learnapollo#79]
After clicking 'Get GraphQL Endpoint (via Github)' on the Get Started page it takes you to a blank screen but nothing loads. I have tried this in a couple of browsers and another computer and I experience the same thing. 

In short, I can't start the interactive tutorial.

Screenshot: 

![image](https://cloud.githubusercontent.com/assets/9679076/26562162/5416efd8-4481-11e7-8a3b-d6933589fdea.png)

**Comment by marktani** [comment]
Does that also happen in an incognito tab?

**Comment by rcwestlake** [comment]
Yes. Screenshot:

![image](https://cloud.githubusercontent.com/assets/9679076/26616009/ad786888-4588-11e7-8a1c-7f8e39b77215.png)

**Comment by marktani** [comment]
Thanks we fixed an issue that might be related. Could you try it again please?

**Comment by rcwestlake** [comment]
Still no luck. Tried Chrome and Firefox private window. 

![image](https://cloud.githubusercontent.com/assets/9679076/26710444/2129e9c0-4717-11e7-9377-382cd49da511.png)

**Comment by talensjr** [comment]
Hi @rcwestlake , I happened to have the same issue than you, but I managed to solve it by copying the ?code=your_code part of the url, and then going to https://www.learnapollo.com/?code=your_code, and then clicking the "Start interactive tutorial" button.
Hope it helps a bit.

**Comment by marktani** [comment]
Hey @rcwestlake, can you try to:
- remove the Learn Apollo authorization from your GitHub account
- logout of GitHub
- try again

**Comment by rcwestlake** [comment]
Success!

**Comment by marktani** [comment]
Awesome! sorry for the inconvenience 🙂
